var rowData = [
  {
    continent: "Europe",
    data: [
      { country: "Denmark", sales: 54, cost: 540, product: "A" },
      { country: "Denmark", sales: 55, cost: 550, product: "A" },
      { country: "Denmark", sales: 55, cost: 550, product: "A" },
      { country: "Denmark", sales: 34, cost: 408, product: "B" },
      { country: "Denmark", sales: 34, cost: 408, product: "B" },
      { country: "Denmark", sales: 34, cost: 408, product: "B" },
      { country: "Denmark", sales: 125, cost: 625, product: "C" },
      { country: "Denmark", sales: 124, cost: 620, product: "C" },
      { country: "Denmark", sales: 124, cost: 620, product: "C" },
      { country: "United Kingdom", sales: 37, cost: 370, product: "A" },
      { country: "United Kingdom", sales: 37, cost: 370, product: "A" },
      { country: "United Kingdom", sales: 37, cost: 370, product: "A" },
      { country: "United Kingdom", sales: 24, cost: 288, product: "B" },
      { country: "United Kingdom", sales: 23, cost: 276, product: "B" },
      { country: "United Kingdom", sales: 23, cost: 276, product: "B" },
      { country: "United Kingdom", sales: 81, cost: 405, product: "C" },
      { country: "United Kingdom", sales: 82, cost: 410, product: "C" },
      { country: "United Kingdom", sales: 82, cost: 410, product: "C" },
      { country: "Bulgaria", sales: 63, cost: 630, product: "A" },
      { country: "Bulgaria", sales: 62, cost: 620, product: "A" },
      { country: "Bulgaria", sales: 62, cost: 620, product: "A" },
      { country: "Bulgaria", sales: 39, cost: 468, product: "B" },
      { country: "Bulgaria", sales: 38, cost: 456, product: "B" },
      { country: "Bulgaria", sales: 38, cost: 456, product: "B" },
      { country: "Bulgaria", sales: 136, cost: 680, product: "C" },
      { country: "Bulgaria", sales: 137, cost: 685, product: "C" },
      { country: "Bulgaria", sales: 137, cost: 685, product: "C" },
      { country: "France", sales: 23, cost: 230, product: "A" },
      { country: "France", sales: 24, cost: 240, product: "A" },
      { country: "France", sales: 24, cost: 240, product: "A" },
      { country: "France", sales: 15, cost: 180, product: "B" },
      { country: "France", sales: 15, cost: 180, product: "B" },
      { country: "France", sales: 15, cost: 180, product: "B" },
      { country: "France", sales: 56, cost: 280, product: "C" },
      { country: "France", sales: 55, cost: 275, product: "C" },
      { country: "France", sales: 55, cost: 275, product: "C" },
      { country: "Germany", sales: 69, cost: 690, product: "A" },
      { country: "Germany", sales: 68, cost: 680, product: "A" },
      { country: "Germany", sales: 68, cost: 680, product: "A" },
      { country: "Germany", sales: 43, cost: 516, product: "B" },
      { country: "Germany", sales: 42, cost: 504, product: "B" },
      { country: "Germany", sales: 42, cost: 504, product: "B" },
      { country: "Germany", sales: 150, cost: 750, product: "C" },
      { country: "Germany", sales: 151, cost: 755, product: "C" },
      { country: "Germany", sales: 151, cost: 755, product: "C" },
      { country: "Latvia", sales: 43, cost: 430, product: "A" },
      { country: "Latvia", sales: 43, cost: 430, product: "A" },
      { country: "Latvia", sales: 43, cost: 430, product: "A" },
      { country: "Latvia", sales: 25, cost: 300, product: "B" },
      { country: "Latvia", sales: 26, cost: 312, product: "B" },
      { country: "Latvia", sales: 26, cost: 312, product: "B" },
      { country: "Latvia", sales: 96, cost: 480, product: "C" },
      { country: "Latvia", sales: 96, cost: 480, product: "C" },
      { country: "Latvia", sales: 96, cost: 480, product: "C" },
      { country: "Hungary", sales: 100, cost: 1000, product: "A" },
      { country: "Hungary", sales: 99, cost: 990, product: "A" },
      { country: "Hungary", sales: 99, cost: 990, product: "A" },
      { country: "Hungary", sales: 62, cost: 744, product: "B" },
      { country: "Hungary", sales: 61, cost: 732, product: "B" },
      { country: "Hungary", sales: 61, cost: 732, product: "B" },
      { country: "Hungary", sales: 220, cost: 1100, product: "C" },
      { country: "Hungary", sales: 220, cost: 1100, product: "C" },
      { country: "Hungary", sales: 220, cost: 1100, product: "C" },
      { country: "Ireland", sales: 74, cost: 740, product: "A" },
      { country: "Ireland", sales: 74, cost: 740, product: "A" },
      { country: "Ireland", sales: 74, cost: 740, product: "A" },
      { country: "Ireland", sales: 44, cost: 528, product: "B" },
      { country: "Ireland", sales: 45, cost: 540, product: "B" },
      { country: "Ireland", sales: 45, cost: 540, product: "B" },
      { country: "Ireland", sales: 165, cost: 825, product: "C" },
      { country: "Ireland", sales: 165, cost: 825, product: "C" },
      { country: "Ireland", sales: 165, cost: 825, product: "C" },
      { country: "Italy", sales: 91, cost: 910, product: "A" },
      { country: "Italy", sales: 92, cost: 920, product: "A" },
      { country: "Italy", sales: 92, cost: 920, product: "A" },
      { country: "Italy", sales: 58, cost: 696, product: "B" },
      { country: "Italy", sales: 57, cost: 684, product: "B" },
      { country: "Italy", sales: 57, cost: 684, product: "B" },
      { country: "Italy", sales: 205, cost: 1025, product: "C" },
      { country: "Italy", sales: 206, cost: 1030, product: "C" },
      { country: "Italy", sales: 206, cost: 1030, product: "C" },
      { country: "Lithuania", sales: 62, cost: 620, product: "A" },
      { country: "Lithuania", sales: 62, cost: 620, product: "A" },
      { country: "Lithuania", sales: 62, cost: 620, product: "A" },
      { country: "Lithuania", sales: 38, cost: 456, product: "B" },
      { country: "Lithuania", sales: 38, cost: 456, product: "B" },
      { country: "Lithuania", sales: 38, cost: 456, product: "B" },
      { country: "Lithuania", sales: 137, cost: 685, product: "C" },
      { country: "Lithuania", sales: 138, cost: 690, product: "C" },
      { country: "Lithuania", sales: 138, cost: 690, product: "C" }
    ],
    sales: 7107,
    cost: 52755
  },

  {
    continent: "South America",
    data: [
      { country: "Argentina", sales: 90, cost: 900, product: "A" },
      { country: "Argentina", sales: 89, cost: 890, product: "A" },
      { country: "Argentina", sales: 89, cost: 890, product: "A" },
      { country: "Argentina", sales: 97, cost: 1164, product: "B" },
      { country: "Argentina", sales: 98, cost: 1176, product: "B" },
      { country: "Argentina", sales: 98, cost: 1176, product: "B" },
      { country: "Argentina", sales: 54, cost: 270, product: "C" },
      { country: "Argentina", sales: 53, cost: 265, product: "C" },
      { country: "Argentina", sales: 53, cost: 265, product: "C" },
      { country: "Bolivia", sales: 59, cost: 590, product: "A" },
      { country: "Bolivia", sales: 59, cost: 590, product: "A" },
      { country: "Bolivia", sales: 59, cost: 590, product: "A" },
      { country: "Bolivia", sales: 67, cost: 804, product: "B" },
      { country: "Bolivia", sales: 66, cost: 792, product: "B" },
      { country: "Bolivia", sales: 66, cost: 792, product: "B" },
      { country: "Bolivia", sales: 35, cost: 175, product: "C" },
      { country: "Bolivia", sales: 35, cost: 175, product: "C" },
      { country: "Bolivia", sales: 35, cost: 175, product: "C" },
      { country: "Brazil", sales: 100, cost: 1000, product: "A" },
      { country: "Brazil", sales: 99, cost: 990, product: "A" },
      { country: "Brazil", sales: 99, cost: 990, product: "A" },
      { country: "Brazil", sales: 108, cost: 1296, product: "B" },
      { country: "Brazil", sales: 109, cost: 1308, product: "B" },
      { country: "Brazil", sales: 109, cost: 1308, product: "B" },
      { country: "Brazil", sales: 60, cost: 300, product: "C" },
      { country: "Brazil", sales: 59, cost: 295, product: "C" },
      { country: "Brazil", sales: 59, cost: 295, product: "C" },
      { country: "Chile", sales: 38, cost: 380, product: "A" },
      { country: "Chile", sales: 39, cost: 390, product: "A" },
      { country: "Chile", sales: 39, cost: 390, product: "A" },
      { country: "Chile", sales: 45, cost: 540, product: "B" },
      { country: "Chile", sales: 44, cost: 528, product: "B" },
      { country: "Chile", sales: 44, cost: 528, product: "B" },
      { country: "Chile", sales: 22, cost: 110, product: "C" },
      { country: "Chile", sales: 23, cost: 115, product: "C" },
      { country: "Chile", sales: 23, cost: 115, product: "C" },
      { country: "Colombia", sales: 110, cost: 1100, product: "A" },
      { country: "Colombia", sales: 109, cost: 1090, product: "A" },
      { country: "Colombia", sales: 109, cost: 1090, product: "A" },
      { country: "Colombia", sales: 119, cost: 1428, product: "B" },
      { country: "Colombia", sales: 120, cost: 1440, product: "B" },
      { country: "Colombia", sales: 120, cost: 1440, product: "B" },
      { country: "Colombia", sales: 66, cost: 330, product: "C" },
      { country: "Colombia", sales: 65, cost: 325, product: "C" },
      { country: "Colombia", sales: 65, cost: 325, product: "C" },
      { country: "Ecuador", sales: 69, cost: 690, product: "A" },
      { country: "Ecuador", sales: 69, cost: 690, product: "A" },
      { country: "Ecuador", sales: 69, cost: 690, product: "A" },
      { country: "Ecuador", sales: 78, cost: 936, product: "B" },
      { country: "Ecuador", sales: 77, cost: 924, product: "B" },
      { country: "Ecuador", sales: 77, cost: 924, product: "B" },
      { country: "Ecuador", sales: 41, cost: 205, product: "C" },
      { country: "Ecuador", sales: 41, cost: 205, product: "C" },
      { country: "Ecuador", sales: 41, cost: 205, product: "C" },
      { country: "Falkland Islands", sales: 158, cost: 1580, product: "A" },
      { country: "Falkland Islands", sales: 158, cost: 1580, product: "A" },
      { country: "Falkland Islands", sales: 158, cost: 1580, product: "A" },
      { country: "Falkland Islands", sales: 174, cost: 2088, product: "B" },
      { country: "Falkland Islands", sales: 175, cost: 2100, product: "B" },
      { country: "Falkland Islands", sales: 175, cost: 2100, product: "B" },
      { country: "Falkland Islands", sales: 94, cost: 470, product: "C" },
      { country: "Falkland Islands", sales: 94, cost: 470, product: "C" },
      { country: "Falkland Islands", sales: 94, cost: 470, product: "C" },
      { country: "French Guiana", sales: 117, cost: 1170, product: "A" },
      { country: "French Guiana", sales: 118, cost: 1180, product: "A" },
      { country: "French Guiana", sales: 118, cost: 1180, product: "A" },
      { country: "French Guiana", sales: 130, cost: 1560, product: "B" },
      { country: "French Guiana", sales: 131, cost: 1572, product: "B" },
      { country: "French Guiana", sales: 131, cost: 1572, product: "B" },
      { country: "French Guiana", sales: 69, cost: 345, product: "C" },
      { country: "French Guiana", sales: 70, cost: 350, product: "C" },
      { country: "French Guiana", sales: 70, cost: 350, product: "C" },
      { country: "Guyana", sales: 147, cost: 1470, product: "A" },
      { country: "Guyana", sales: 148, cost: 1480, product: "A" },
      { country: "Guyana", sales: 148, cost: 1480, product: "A" },
      { country: "Guyana", sales: 163, cost: 1956, product: "B" },
      { country: "Guyana", sales: 164, cost: 1968, product: "B" },
      { country: "Guyana", sales: 164, cost: 1968, product: "B" },
      { country: "Guyana", sales: 88, cost: 440, product: "C" },
      { country: "Guyana", sales: 88, cost: 440, product: "C" },
      { country: "Guyana", sales: 88, cost: 440, product: "C" },
      { country: "Paraguay", sales: 99, cost: 990, product: "A" },
      { country: "Paraguay", sales: 99, cost: 990, product: "A" },
      { country: "Paraguay", sales: 99, cost: 990, product: "A" },
      { country: "Paraguay", sales: 110, cost: 1320, product: "B" },
      { country: "Paraguay", sales: 110, cost: 1320, product: "B" },
      { country: "Paraguay", sales: 110, cost: 1320, product: "B" },
      { country: "Paraguay", sales: 59, cost: 295, product: "C" },
      { country: "Paraguay", sales: 59, cost: 295, product: "C" },
      { country: "Paraguay", sales: 59, cost: 295, product: "C" }
    ],
    sales: 8002,
    cost: 77768
  },
  {
    continent: "North America",
    data: [
      { country: "United States", sales: 174, cost: 1740, product: "A" },
      { country: "United States", sales: 173, cost: 1730, product: "A" },
      { country: "United States", sales: 173, cost: 1730, product: "A" },
      { country: "United States", sales: 25, cost: 300, product: "B" },
      { country: "United States", sales: 25, cost: 300, product: "B" },
      { country: "United States", sales: 25, cost: 300, product: "B" },
      { country: "United States", sales: 51, cost: 255, product: "C" },
      { country: "United States", sales: 52, cost: 260, product: "C" },
      { country: "United States", sales: 52, cost: 260, product: "C" },
      { country: "Mexico", sales: 115, cost: 1150, product: "A" },
      { country: "Mexico", sales: 115, cost: 1150, product: "A" },
      { country: "Mexico", sales: 115, cost: 1150, product: "A" },
      { country: "Mexico", sales: 18, cost: 216, product: "B" },
      { country: "Mexico", sales: 17, cost: 204, product: "B" },
      { country: "Mexico", sales: 17, cost: 204, product: "B" },
      { country: "Mexico", sales: 35, cost: 175, product: "C" },
      { country: "Mexico", sales: 35, cost: 175, product: "C" },
      { country: "Mexico", sales: 35, cost: 175, product: "C" },
      { country: "Canada", sales: 192, cost: 1920, product: "A" },
      { country: "Canada", sales: 192, cost: 1920, product: "A" },
      { country: "Canada", sales: 192, cost: 1920, product: "A" },
      { country: "Canada", sales: 29, cost: 348, product: "B" },
      { country: "Canada", sales: 28, cost: 336, product: "B" },
      { country: "Canada", sales: 28, cost: 336, product: "B" },
      { country: "Canada", sales: 57, cost: 285, product: "C" },
      { country: "Canada", sales: 58, cost: 290, product: "C" },
      { country: "Canada", sales: 58, cost: 290, product: "C" },
      { country: "Jamaica", sales: 78, cost: 780, product: "A" },
      { country: "Jamaica", sales: 77, cost: 770, product: "A" },
      { country: "Jamaica", sales: 77, cost: 770, product: "A" },
      { country: "Jamaica", sales: 11, cost: 132, product: "B" },
      { country: "Jamaica", sales: 11, cost: 132, product: "B" },
      { country: "Jamaica", sales: 11, cost: 132, product: "B" },
      { country: "Jamaica", sales: 22, cost: 110, product: "C" },
      { country: "Jamaica", sales: 23, cost: 115, product: "C" },
      { country: "Jamaica", sales: 23, cost: 115, product: "C" },
      { country: "Barbados", sales: 210, cost: 2100, product: "A" },
      { country: "Barbados", sales: 211, cost: 2110, product: "A" },
      { country: "Barbados", sales: 211, cost: 2110, product: "A" },
      { country: "Barbados", sales: 29, cost: 348, product: "B" },
      { country: "Barbados", sales: 30, cost: 360, product: "B" },
      { country: "Barbados", sales: 30, cost: 360, product: "B" },
      { country: "Barbados", sales: 64, cost: 320, product: "C" },
      { country: "Barbados", sales: 64, cost: 320, product: "C" },
      { country: "Barbados", sales: 64, cost: 320, product: "C" },
      { country: "Dominica", sales: 134, cost: 1340, product: "A" },
      { country: "Dominica", sales: 134, cost: 1340, product: "A" },
      { country: "Dominica", sales: 134, cost: 1340, product: "A" },
      { country: "Dominica", sales: 18, cost: 216, product: "B" },
      { country: "Dominica", sales: 19, cost: 228, product: "B" },
      { country: "Dominica", sales: 19, cost: 228, product: "B" },
      { country: "Dominica", sales: 42, cost: 210, product: "C" },
      { country: "Dominica", sales: 41, cost: 205, product: "C" },
      { country: "Dominica", sales: 41, cost: 205, product: "C" },
      { country: "Belize", sales: 306, cost: 3060, product: "A" },
      { country: "Belize", sales: 307, cost: 3070, product: "A" },
      { country: "Belize", sales: 307, cost: 3070, product: "A" },
      { country: "Belize", sales: 43, cost: 516, product: "B" },
      { country: "Belize", sales: 44, cost: 528, product: "B" },
      { country: "Belize", sales: 44, cost: 528, product: "B" },
      { country: "Belize", sales: 92, cost: 460, product: "C" },
      { country: "Belize", sales: 93, cost: 465, product: "C" },
      { country: "Belize", sales: 93, cost: 465, product: "C" },
      { country: "Guadalupe", sales: 229, cost: 2290, product: "A" },
      { country: "Guadalupe", sales: 230, cost: 2300, product: "A" },
      { country: "Guadalupe", sales: 230, cost: 2300, product: "A" },
      { country: "Guadalupe", sales: 32, cost: 384, product: "B" },
      { country: "Guadalupe", sales: 33, cost: 396, product: "B" },
      { country: "Guadalupe", sales: 33, cost: 396, product: "B" },
      { country: "Guadalupe", sales: 70, cost: 350, product: "C" },
      { country: "Guadalupe", sales: 70, cost: 350, product: "C" },
      { country: "Guadalupe", sales: 70, cost: 350, product: "C" },
      { country: "Trinidad and Tobago", sales: 288, cost: 2880, product: "A" },
      { country: "Trinidad and Tobago", sales: 288, cost: 2880, product: "A" },
      { country: "Trinidad and Tobago", sales: 288, cost: 2880, product: "A" },
      { country: "Trinidad and Tobago", sales: 43, cost: 516, product: "B" },
      { country: "Trinidad and Tobago", sales: 42, cost: 504, product: "B" },
      { country: "Trinidad and Tobago", sales: 42, cost: 504, product: "B" },
      { country: "Trinidad and Tobago", sales: 89, cost: 445, product: "C" },
      { country: "Trinidad and Tobago", sales: 88, cost: 440, product: "C" },
      { country: "Trinidad and Tobago", sales: 88, cost: 440, product: "C" },
      {
        country: "Saint Vincent and the Grenadines",
        sales: 193,
        cost: 1930,
        product: "A"
      },
      {
        country: "Saint Vincent and the Grenadines",
        sales: 193,
        cost: 1930,
        product: "A"
      },
      {
        country: "Saint Vincent and the Grenadines",
        sales: 193,
        cost: 1930,
        product: "A"
      },
      {
        country: "Saint Vincent and the Grenadines",
        sales: 28,
        cost: 336,
        product: "B"
      },
      {
        country: "Saint Vincent and the Grenadines",
        sales: 28,
        cost: 336,
        product: "B"
      },
      {
        country: "Saint Vincent and the Grenadines",
        sales: 28,
        cost: 336,
        product: "B"
      },
      {
        country: "Saint Vincent and the Grenadines",
        sales: 60,
        cost: 300,
        product: "C"
      },
      {
        country: "Saint Vincent and the Grenadines",
        sales: 59,
        cost: 295,
        product: "C"
      },
      {
        country: "Saint Vincent and the Grenadines",
        sales: 59,
        cost: 295,
        product: "C"
      }
    ],
    sales: 8337,
    cost: 76290
  },
  {
    continent: "Asia",
    data: [
      { country: "China", sales: 40, cost: 400, product: "A" },
      { country: "China", sales: 39, cost: 390, product: "A" },
      { country: "China", sales: 39, cost: 390, product: "A" },
      { country: "China", sales: 76, cost: 912, product: "B" },
      { country: "China", sales: 75, cost: 900, product: "B" },
      { country: "China", sales: 75, cost: 900, product: "B" },
      { country: "China", sales: 162, cost: 810, product: "C" },
      { country: "China", sales: 163, cost: 815, product: "C" },
      { country: "China", sales: 163, cost: 815, product: "C" },
      { country: "Japan", sales: 27, cost: 270, product: "A" },
      { country: "Japan", sales: 26, cost: 260, product: "A" },
      { country: "Japan", sales: 26, cost: 260, product: "A" },
      { country: "Japan", sales: 51, cost: 612, product: "B" },
      { country: "Japan", sales: 50, cost: 600, product: "B" },
      { country: "Japan", sales: 50, cost: 600, product: "B" },
      { country: "Japan", sales: 109, cost: 545, product: "C" },
      { country: "Japan", sales: 109, cost: 545, product: "C" },
      { country: "Japan", sales: 109, cost: 545, product: "C" },
      { country: "India", sales: 43, cost: 430, product: "A" },
      { country: "India", sales: 43, cost: 430, product: "A" },
      { country: "India", sales: 43, cost: 430, product: "A" },
      { country: "India", sales: 83, cost: 996, product: "B" },
      { country: "India", sales: 83, cost: 996, product: "B" },
      { country: "India", sales: 83, cost: 996, product: "B" },
      { country: "India", sales: 183, cost: 915, product: "C" },
      { country: "India", sales: 182, cost: 910, product: "C" },
      { country: "India", sales: 182, cost: 910, product: "C" },
      { country: "Pakistan", sales: 17, cost: 170, product: "A" },
      { country: "Pakistan", sales: 17, cost: 170, product: "A" },
      { country: "Pakistan", sales: 17, cost: 170, product: "A" },
      { country: "Pakistan", sales: 33, cost: 396, product: "B" },
      { country: "Pakistan", sales: 33, cost: 396, product: "B" },
      { country: "Pakistan", sales: 33, cost: 396, product: "B" },
      { country: "Pakistan", sales: 74, cost: 370, product: "C" },
      { country: "Pakistan", sales: 73, cost: 365, product: "C" },
      { country: "Pakistan", sales: 73, cost: 365, product: "C" },
      { country: "Russia", sales: 46, cost: 460, product: "A" },
      { country: "Russia", sales: 47, cost: 470, product: "A" },
      { country: "Russia", sales: 47, cost: 470, product: "A" },
      { country: "Russia", sales: 90, cost: 1080, product: "B" },
      { country: "Russia", sales: 91, cost: 1092, product: "B" },
      { country: "Russia", sales: 91, cost: 1092, product: "B" },
      { country: "Russia", sales: 200, cost: 1000, product: "C" },
      { country: "Russia", sales: 200, cost: 1000, product: "C" },
      { country: "Russia", sales: 200, cost: 1000, product: "C" },
      { country: "Sri-Lanka", sales: 30, cost: 300, product: "A" },
      { country: "Sri-Lanka", sales: 30, cost: 300, product: "A" },
      { country: "Sri-Lanka", sales: 30, cost: 300, product: "A" },
      { country: "Sri-Lanka", sales: 58, cost: 696, product: "B" },
      { country: "Sri-Lanka", sales: 58, cost: 696, product: "B" },
      { country: "Sri-Lanka", sales: 58, cost: 696, product: "B" },
      { country: "Sri-Lanka", sales: 127, cost: 635, product: "C" },
      { country: "Sri-Lanka", sales: 127, cost: 635, product: "C" },
      { country: "Sri-Lanka", sales: 127, cost: 635, product: "C" },
      { country: "Iran", sales: 69, cost: 690, product: "A" },
      { country: "Iran", sales: 69, cost: 690, product: "A" },
      { country: "Iran", sales: 69, cost: 690, product: "A" },
      { country: "Iran", sales: 133, cost: 1596, product: "B" },
      { country: "Iran", sales: 133, cost: 1596, product: "B" },
      { country: "Iran", sales: 133, cost: 1596, product: "B" },
      { country: "Iran", sales: 291, cost: 1455, product: "C" },
      { country: "Iran", sales: 291, cost: 1455, product: "C" },
      { country: "Iran", sales: 291, cost: 1455, product: "C" },
      { country: "Vietnam", sales: 53, cost: 530, product: "A" },
      { country: "Vietnam", sales: 52, cost: 520, product: "A" },
      { country: "Vietnam", sales: 52, cost: 520, product: "A" },
      { country: "Vietnam", sales: 101, cost: 1212, product: "B" },
      { country: "Vietnam", sales: 100, cost: 1200, product: "B" },
      { country: "Vietnam", sales: 100, cost: 1200, product: "B" },
      { country: "Vietnam", sales: 218, cost: 1090, product: "C" },
      { country: "Vietnam", sales: 218, cost: 1090, product: "C" },
      { country: "Vietnam", sales: 218, cost: 1090, product: "C" },
      { country: "Bangladesh", sales: 66, cost: 660, product: "A" },
      { country: "Bangladesh", sales: 65, cost: 650, product: "A" },
      { country: "Bangladesh", sales: 65, cost: 650, product: "A" },
      { country: "Bangladesh", sales: 126, cost: 1512, product: "B" },
      { country: "Bangladesh", sales: 125, cost: 1500, product: "B" },
      { country: "Bangladesh", sales: 125, cost: 1500, product: "B" },
      { country: "Bangladesh", sales: 274, cost: 1370, product: "C" },
      { country: "Bangladesh", sales: 273, cost: 1365, product: "C" },
      { country: "Bangladesh", sales: 273, cost: 1365, product: "C" },
      { country: "Philippines", sales: 42, cost: 420, product: "A" },
      { country: "Philippines", sales: 43, cost: 430, product: "A" },
      { country: "Philippines", sales: 43, cost: 430, product: "A" },
      { country: "Philippines", sales: 85, cost: 1020, product: "B" },
      { country: "Philippines", sales: 84, cost: 1008, product: "B" },
      { country: "Philippines", sales: 84, cost: 1008, product: "B" },
      { country: "Philippines", sales: 184, cost: 920, product: "C" },
      { country: "Philippines", sales: 183, cost: 915, product: "C" },
      { country: "Philippines", sales: 183, cost: 915, product: "C" }
    ],
    sales: 9255,
    cost: 70250
  },
  {
    continent: "Africa",
    data: [
      { country: "Nigeria", sales: 78, cost: 780, product: "A" },
      { country: "Nigeria", sales: 77, cost: 770, product: "A" },
      { country: "Nigeria", sales: 77, cost: 770, product: "A" },
      { country: "Nigeria", sales: 121, cost: 1452, product: "B" },
      { country: "Nigeria", sales: 122, cost: 1464, product: "B" },
      { country: "Nigeria", sales: 122, cost: 1464, product: "B" },
      { country: "Nigeria", sales: 42, cost: 210, product: "C" },
      { country: "Nigeria", sales: 41, cost: 205, product: "C" },
      { country: "Nigeria", sales: 41, cost: 205, product: "C" },
      { country: "Ethiopia", sales: 51, cost: 510, product: "A" },
      { country: "Ethiopia", sales: 51, cost: 510, product: "A" },
      { country: "Ethiopia", sales: 51, cost: 510, product: "A" },
      { country: "Ethiopia", sales: 83, cost: 996, product: "B" },
      { country: "Ethiopia", sales: 82, cost: 984, product: "B" },
      { country: "Ethiopia", sales: 82, cost: 984, product: "B" },
      { country: "Ethiopia", sales: 27, cost: 135, product: "C" },
      { country: "Ethiopia", sales: 27, cost: 135, product: "C" },
      { country: "Ethiopia", sales: 27, cost: 135, product: "C" },
      { country: "Egypt", sales: 84, cost: 840, product: "A" },
      { country: "Egypt", sales: 85, cost: 850, product: "A" },
      { country: "Egypt", sales: 85, cost: 850, product: "A" },
      { country: "Egypt", sales: 135, cost: 1620, product: "B" },
      { country: "Egypt", sales: 136, cost: 1632, product: "B" },
      { country: "Egypt", sales: 136, cost: 1632, product: "B" },
      { country: "Egypt", sales: 44, cost: 220, product: "C" },
      { country: "Egypt", sales: 45, cost: 225, product: "C" },
      { country: "Egypt", sales: 45, cost: 225, product: "C" },
      {
        country: "Democratic Republic of the Congo",
        sales: 34,
        cost: 340,
        product: "A"
      },
      {
        country: "Democratic Republic of the Congo",
        sales: 34,
        cost: 340,
        product: "A"
      },
      {
        country: "Democratic Republic of the Congo",
        sales: 34,
        cost: 340,
        product: "A"
      },
      {
        country: "Democratic Republic of the Congo",
        sales: 53,
        cost: 636,
        product: "B"
      },
      {
        country: "Democratic Republic of the Congo",
        sales: 54,
        cost: 648,
        product: "B"
      },
      {
        country: "Democratic Republic of the Congo",
        sales: 54,
        cost: 648,
        product: "B"
      },
      {
        country: "Democratic Republic of the Congo",
        sales: 18,
        cost: 90,
        product: "C"
      },
      {
        country: "Democratic Republic of the Congo",
        sales: 18,
        cost: 90,
        product: "C"
      },
      {
        country: "Democratic Republic of the Congo",
        sales: 18,
        cost: 90,
        product: "C"
      },
      { country: "Tanzania", sales: 94, cost: 940, product: "A" },
      { country: "Tanzania", sales: 94, cost: 940, product: "A" },
      { country: "Tanzania", sales: 94, cost: 940, product: "A" },
      { country: "Tanzania", sales: 151, cost: 1812, product: "B" },
      { country: "Tanzania", sales: 150, cost: 1800, product: "B" },
      { country: "Tanzania", sales: 150, cost: 1800, product: "B" },
      { country: "Tanzania", sales: 51, cost: 255, product: "C" },
      { country: "Tanzania", sales: 50, cost: 250, product: "C" },
      { country: "Tanzania", sales: 50, cost: 250, product: "C" },
      { country: "South Africa", sales: 61, cost: 610, product: "A" },
      { country: "South Africa", sales: 60, cost: 600, product: "A" },
      { country: "South Africa", sales: 60, cost: 600, product: "A" },
      { country: "South Africa", sales: 94, cost: 1128, product: "B" },
      { country: "South Africa", sales: 95, cost: 1140, product: "B" },
      { country: "South Africa", sales: 95, cost: 1140, product: "B" },
      { country: "South Africa", sales: 33, cost: 165, product: "C" },
      { country: "South Africa", sales: 32, cost: 160, product: "C" },
      { country: "South Africa", sales: 32, cost: 160, product: "C" },
      { country: "Kenya", sales: 138, cost: 1380, product: "A" },
      { country: "Kenya", sales: 137, cost: 1370, product: "A" },
      { country: "Kenya", sales: 137, cost: 1370, product: "A" },
      { country: "Kenya", sales: 218, cost: 2616, product: "B" },
      { country: "Kenya", sales: 218, cost: 2616, product: "B" },
      { country: "Kenya", sales: 218, cost: 2616, product: "B" },
      { country: "Kenya", sales: 74, cost: 370, product: "C" },
      { country: "Kenya", sales: 73, cost: 365, product: "C" },
      { country: "Kenya", sales: 73, cost: 365, product: "C" },
      { country: "Uganda", sales: 101, cost: 1010, product: "A" },
      { country: "Uganda", sales: 102, cost: 1020, product: "A" },
      { country: "Uganda", sales: 102, cost: 1020, product: "A" },
      { country: "Uganda", sales: 162, cost: 1944, product: "B" },
      { country: "Uganda", sales: 163, cost: 1956, product: "B" },
      { country: "Uganda", sales: 163, cost: 1956, product: "B" },
      { country: "Uganda", sales: 53, cost: 265, product: "C" },
      { country: "Uganda", sales: 54, cost: 270, product: "C" },
      { country: "Uganda", sales: 54, cost: 270, product: "C" },
      { country: "Algeria", sales: 128, cost: 1280, product: "A" },
      { country: "Algeria", sales: 128, cost: 1280, product: "A" },
      { country: "Algeria", sales: 128, cost: 1280, product: "A" },
      { country: "Algeria", sales: 203, cost: 2436, product: "B" },
      { country: "Algeria", sales: 204, cost: 2448, product: "B" },
      { country: "Algeria", sales: 204, cost: 2448, product: "B" },
      { country: "Algeria", sales: 68, cost: 340, product: "C" },
      { country: "Algeria", sales: 68, cost: 340, product: "C" },
      { country: "Algeria", sales: 68, cost: 340, product: "C" },
      { country: "Sudan", sales: 87, cost: 870, product: "A" },
      { country: "Sudan", sales: 86, cost: 860, product: "A" },
      { country: "Sudan", sales: 86, cost: 860, product: "A" },
      { country: "Sudan", sales: 137, cost: 1644, product: "B" },
      { country: "Sudan", sales: 137, cost: 1644, product: "B" },
      { country: "Sudan", sales: 137, cost: 1644, product: "B" },
      { country: "Sudan", sales: 47, cost: 235, product: "C" },
      { country: "Sudan", sales: 46, cost: 230, product: "C" },
      { country: "Sudan", sales: 46, cost: 230, product: "C" }
    ],
    sales: 8008,
    cost: 81413
  },
  {
    continent: "Australia",
    data: [
      { country: "Australia", sales: 81, cost: 810, product: "A" },
      { country: "Australia", sales: 82, cost: 820, product: "A" },
      { country: "Australia", sales: 82, cost: 820, product: "A" },
      { country: "Australia", sales: 72, cost: 864, product: "B" },
      { country: "Australia", sales: 73, cost: 876, product: "B" },
      { country: "Australia", sales: 73, cost: 876, product: "B" },
      { country: "Australia", sales: 72, cost: 360, product: "C" },
      { country: "Australia", sales: 73, cost: 365, product: "C" },
      { country: "Australia", sales: 73, cost: 365, product: "C" },
      { country: "Micronesia", sales: 56, cost: 560, product: "A" },
      { country: "Micronesia", sales: 55, cost: 550, product: "A" },
      { country: "Micronesia", sales: 55, cost: 550, product: "A" },
      { country: "Micronesia", sales: 50, cost: 600, product: "B" },
      { country: "Micronesia", sales: 49, cost: 588, product: "B" },
      { country: "Micronesia", sales: 49, cost: 588, product: "B" },
      { country: "Micronesia", sales: 50, cost: 250, product: "C" },
      { country: "Micronesia", sales: 49, cost: 245, product: "C" },
      { country: "Micronesia", sales: 49, cost: 245, product: "C" },
      { country: "Fiji", sales: 93, cost: 930, product: "A" },
      { country: "Fiji", sales: 92, cost: 920, product: "A" },
      { country: "Fiji", sales: 92, cost: 920, product: "A" },
      { country: "Fiji", sales: 80, cost: 960, product: "B" },
      { country: "Fiji", sales: 81, cost: 972, product: "B" },
      { country: "Fiji", sales: 81, cost: 972, product: "B" },
      { country: "Fiji", sales: 80, cost: 400, product: "C" },
      { country: "Fiji", sales: 81, cost: 405, product: "C" },
      { country: "Fiji", sales: 81, cost: 405, product: "C" },
      { country: "Kiribati", sales: 35, cost: 350, product: "A" },
      { country: "Kiribati", sales: 36, cost: 360, product: "A" },
      { country: "Kiribati", sales: 36, cost: 360, product: "A" },
      { country: "Kiribati", sales: 31, cost: 372, product: "B" },
      { country: "Kiribati", sales: 32, cost: 384, product: "B" },
      { country: "Kiribati", sales: 32, cost: 384, product: "B" },
      { country: "Kiribati", sales: 31, cost: 155, product: "C" },
      { country: "Kiribati", sales: 32, cost: 160, product: "C" },
      { country: "Kiribati", sales: 32, cost: 160, product: "C" },
      { country: "Marshall Islands", sales: 102, cost: 1020, product: "A" },
      { country: "Marshall Islands", sales: 101, cost: 1010, product: "A" },
      { country: "Marshall Islands", sales: 101, cost: 1010, product: "A" },
      { country: "Marshall Islands", sales: 91, cost: 1092, product: "B" },
      { country: "Marshall Islands", sales: 90, cost: 1080, product: "B" },
      { country: "Marshall Islands", sales: 90, cost: 1080, product: "B" },
      { country: "Marshall Islands", sales: 91, cost: 455, product: "C" },
      { country: "Marshall Islands", sales: 90, cost: 450, product: "C" },
      { country: "Marshall Islands", sales: 90, cost: 450, product: "C" },
      { country: "Nauru", sales: 64, cost: 640, product: "A" },
      { country: "Nauru", sales: 64, cost: 640, product: "A" },
      { country: "Nauru", sales: 64, cost: 640, product: "A" },
      { country: "Nauru", sales: 57, cost: 684, product: "B" },
      { country: "Nauru", sales: 57, cost: 684, product: "B" },
      { country: "Nauru", sales: 57, cost: 684, product: "B" },
      { country: "Nauru", sales: 57, cost: 285, product: "C" },
      { country: "Nauru", sales: 57, cost: 285, product: "C" },
      { country: "Nauru", sales: 57, cost: 285, product: "C" },
      { country: "New Zealand", sales: 148, cost: 1480, product: "A" },
      { country: "New Zealand", sales: 147, cost: 1470, product: "A" },
      { country: "New Zealand", sales: 147, cost: 1470, product: "A" },
      { country: "New Zealand", sales: 129, cost: 1548, product: "B" },
      { country: "New Zealand", sales: 130, cost: 1560, product: "B" },
      { country: "New Zealand", sales: 130, cost: 1560, product: "B" },
      { country: "New Zealand", sales: 129, cost: 645, product: "C" },
      { country: "New Zealand", sales: 130, cost: 650, product: "C" },
      { country: "New Zealand", sales: 130, cost: 650, product: "C" },
      { country: "Palau", sales: 110, cost: 1100, product: "A" },
      { country: "Palau", sales: 110, cost: 1100, product: "A" },
      { country: "Palau", sales: 110, cost: 1100, product: "A" },
      { country: "Palau", sales: 99, cost: 1188, product: "B" },
      { country: "Palau", sales: 98, cost: 1176, product: "B" },
      { country: "Palau", sales: 98, cost: 1176, product: "B" },
      { country: "Palau", sales: 99, cost: 495, product: "C" },
      { country: "Palau", sales: 98, cost: 490, product: "C" },
      { country: "Palau", sales: 98, cost: 490, product: "C" },
      { country: "Papua New Guinea", sales: 136, cost: 1360, product: "A" },
      { country: "Papua New Guinea", sales: 137, cost: 1370, product: "A" },
      { country: "Papua New Guinea", sales: 137, cost: 1370, product: "A" },
      { country: "Papua New Guinea", sales: 121, cost: 1452, product: "B" },
      { country: "Papua New Guinea", sales: 122, cost: 1464, product: "B" },
      { country: "Papua New Guinea", sales: 122, cost: 1464, product: "B" },
      { country: "Papua New Guinea", sales: 121, cost: 605, product: "C" },
      { country: "Papua New Guinea", sales: 122, cost: 610, product: "C" },
      { country: "Papua New Guinea", sales: 122, cost: 610, product: "C" },
      { country: "Samoa", sales: 91, cost: 910, product: "A" },
      { country: "Samoa", sales: 92, cost: 920, product: "A" },
      { country: "Samoa", sales: 92, cost: 920, product: "A" },
      { country: "Samoa", sales: 82, cost: 984, product: "B" },
      { country: "Samoa", sales: 82, cost: 984, product: "B" },
      { country: "Samoa", sales: 82, cost: 984, product: "B" },
      { country: "Samoa", sales: 82, cost: 410, product: "C" },
      { country: "Samoa", sales: 82, cost: 410, product: "C" },
      { country: "Samoa", sales: 82, cost: 410, product: "C" }
    ],
    sales: 7628,
    cost: 68960
  },
  {
    continent: "Antarctica",
    data: [
      { country: "Adélie Land", sales: 99, cost: 990, product: "A" },
      { country: "Adélie Land", sales: 98, cost: 980, product: "A" },
      { country: "Adélie Land", sales: 98, cost: 980, product: "A" },
      { country: "Adélie Land", sales: 45, cost: 540, product: "B" },
      { country: "Adélie Land", sales: 45, cost: 540, product: "B" },
      { country: "Adélie Land", sales: 45, cost: 540, product: "B" },
      { country: "Adélie Land", sales: 45, cost: 225, product: "C" },
      { country: "Adélie Land", sales: 45, cost: 225, product: "C" },
      { country: "Adélie Land", sales: 45, cost: 225, product: "C" },
      {
        country: "British Antarctic Territory",
        sales: 65,
        cost: 650,
        product: "A"
      },
      {
        country: "British Antarctic Territory",
        sales: 65,
        cost: 650,
        product: "A"
      },
      {
        country: "British Antarctic Territory",
        sales: 65,
        cost: 650,
        product: "A"
      },
      {
        country: "British Antarctic Territory",
        sales: 30,
        cost: 360,
        product: "B"
      },
      {
        country: "British Antarctic Territory",
        sales: 30,
        cost: 360,
        product: "B"
      },
      {
        country: "British Antarctic Territory",
        sales: 30,
        cost: 360,
        product: "B"
      },
      {
        country: "British Antarctic Territory",
        sales: 30,
        cost: 150,
        product: "C"
      },
      {
        country: "British Antarctic Territory",
        sales: 30,
        cost: 150,
        product: "C"
      },
      {
        country: "British Antarctic Territory",
        sales: 30,
        cost: 150,
        product: "C"
      },
      { country: "Ross Dependency", sales: 110, cost: 1100, product: "A" },
      { country: "Ross Dependency", sales: 109, cost: 1090, product: "A" },
      { country: "Ross Dependency", sales: 109, cost: 1090, product: "A" },
      { country: "Ross Dependency", sales: 50, cost: 600, product: "B" },
      { country: "Ross Dependency", sales: 50, cost: 600, product: "B" },
      { country: "Ross Dependency", sales: 50, cost: 600, product: "B" },
      { country: "Ross Dependency", sales: 50, cost: 250, product: "C" },
      { country: "Ross Dependency", sales: 50, cost: 250, product: "C" },
      { country: "Ross Dependency", sales: 50, cost: 250, product: "C" },
      {
        country: "Peter I Island and Queen Maud Land",
        sales: 42,
        cost: 420,
        product: "A"
      },
      {
        country: "Peter I Island and Queen Maud Land",
        sales: 43,
        cost: 430,
        product: "A"
      },
      {
        country: "Peter I Island and Queen Maud Land",
        sales: 43,
        cost: 430,
        product: "A"
      },
      {
        country: "Peter I Island and Queen Maud Land",
        sales: 20,
        cost: 240,
        product: "B"
      },
      {
        country: "Peter I Island and Queen Maud Land",
        sales: 20,
        cost: 240,
        product: "B"
      },
      {
        country: "Peter I Island and Queen Maud Land",
        sales: 20,
        cost: 240,
        product: "B"
      },
      {
        country: "Peter I Island and Queen Maud Land",
        sales: 20,
        cost: 100,
        product: "C"
      },
      {
        country: "Peter I Island and Queen Maud Land",
        sales: 20,
        cost: 100,
        product: "C"
      },
      {
        country: "Peter I Island and Queen Maud Land",
        sales: 20,
        cost: 100,
        product: "C"
      },
      {
        country: "Australian Antarctic Territory",
        sales: 121,
        cost: 1210,
        product: "A"
      },
      {
        country: "Australian Antarctic Territory",
        sales: 120,
        cost: 1200,
        product: "A"
      },
      {
        country: "Australian Antarctic Territory",
        sales: 120,
        cost: 1200,
        product: "A"
      },
      {
        country: "Australian Antarctic Territory",
        sales: 55,
        cost: 660,
        product: "B"
      },
      {
        country: "Australian Antarctic Territory",
        sales: 55,
        cost: 660,
        product: "B"
      },
      {
        country: "Australian Antarctic Territory",
        sales: 55,
        cost: 660,
        product: "B"
      },
      {
        country: "Australian Antarctic Territory",
        sales: 55,
        cost: 275,
        product: "C"
      },
      {
        country: "Australian Antarctic Territory",
        sales: 55,
        cost: 275,
        product: "C"
      },
      {
        country: "Australian Antarctic Territory",
        sales: 55,
        cost: 275,
        product: "C"
      },
      {
        country: "Chilean Antarctic Territory",
        sales: 76,
        cost: 760,
        product: "A"
      },
      {
        country: "Chilean Antarctic Territory",
        sales: 76,
        cost: 760,
        product: "A"
      },
      {
        country: "Chilean Antarctic Territory",
        sales: 76,
        cost: 760,
        product: "A"
      },
      {
        country: "Chilean Antarctic Territory",
        sales: 35,
        cost: 420,
        product: "B"
      },
      {
        country: "Chilean Antarctic Territory",
        sales: 35,
        cost: 420,
        product: "B"
      },
      {
        country: "Chilean Antarctic Territory",
        sales: 35,
        cost: 420,
        product: "B"
      },
      {
        country: "Chilean Antarctic Territory",
        sales: 35,
        cost: 175,
        product: "C"
      },
      {
        country: "Chilean Antarctic Territory",
        sales: 35,
        cost: 175,
        product: "C"
      },
      {
        country: "Chilean Antarctic Territory",
        sales: 35,
        cost: 175,
        product: "C"
      },
      { country: "Argentine Antarctica", sales: 174, cost: 1740, product: "A" },
      { country: "Argentine Antarctica", sales: 174, cost: 1740, product: "A" },
      { country: "Argentine Antarctica", sales: 174, cost: 1740, product: "A" },
      { country: "Argentine Antarctica", sales: 79, cost: 948, product: "B" },
      { country: "Argentine Antarctica", sales: 80, cost: 960, product: "B" },
      { country: "Argentine Antarctica", sales: 80, cost: 960, product: "B" },
      { country: "Argentine Antarctica", sales: 79, cost: 395, product: "C" },
      { country: "Argentine Antarctica", sales: 80, cost: 400, product: "C" },
      { country: "Argentine Antarctica", sales: 80, cost: 400, product: "C" }
    ],
    sales: 3945,
    cost: 36618
  }
];
export default rowData;
